version: '2'

services:
    festival_cms_db:
        image: postgres        
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: app
        ports:
          - "5432:5432"
